# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e60e7d7df0bd0c9279dc812041e250aa"
name = "order-limit"
handle = "order-limit-9"
application_url = "https://module-coaching-addition-provide.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5073196b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_publications,write_products"

[auth]
redirect_urls = [
  "https://module-coaching-addition-provide.trycloudflare.com/auth/callback",
  "https://module-coaching-addition-provide.trycloudflare.com/auth/shopify/callback",
  "https://module-coaching-addition-provide.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
