# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39c03c0ba0965aba6f40b779e1eb966f"
name = "CartControl: Order Limit"
handle = "cartcontrol-order-limit"
application_url = "https://order-limit-lcxo.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-655031d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_publications,write_customers,write_products"

[auth]
redirect_urls = [
  "https://order-limit-lcxo.onrender.com/auth/callback",
  "https://order-limit-lcxo.onrender.com/auth/shopify/callback",
  "https://order-limit-lcxo.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
