# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02ab6817b4708644340987acd47ac849"
name = "order-limit"
handle = "order-limit-9"
application_url = "https://leone-faq-invitations-rotation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0e68b6ec.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://leone-faq-invitations-rotation.trycloudflare.com/auth/callback",
  "https://leone-faq-invitations-rotation.trycloudflare.com/auth/shopify/callback",
  "https://leone-faq-invitations-rotation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
