# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ab151268aabaa04955221ac59b04edc"
name = "CartControl: Order Limit(dev)"
handle = "cartcontrol-order-limit-dev"
application_url = "https://variance-accessories-deposit-headquarters.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-prev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_publications,write_customers,write_products"

[auth]
redirect_urls = [
  "https://variance-accessories-deposit-headquarters.trycloudflare.com/auth/callback",
  "https://variance-accessories-deposit-headquarters.trycloudflare.com/auth/shopify/callback",
  "https://variance-accessories-deposit-headquarters.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
