# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "495b7af9a29dd8a1c2b0f9fb4eed45fa"
name = "order-limit-2"
handle = "order-limit-18"
application_url = "https://perl-seal-objective-js.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "orderlimt.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_publications,write_products"

[auth]
redirect_urls = [
  "https://perl-seal-objective-js.trycloudflare.com/auth/callback",
  "https://perl-seal-objective-js.trycloudflare.com/auth/shopify/callback",
  "https://perl-seal-objective-js.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
