# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39c03c0ba0965aba6f40b779e1eb966f"
name = "Order Limit"
handle = "order-limit-20"
application_url = "https://hrs-requiring-cave-willing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-655031d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_publications,write_products"

[auth]
redirect_urls = [
  "https://hrs-requiring-cave-willing.trycloudflare.com/auth/callback",
  "https://hrs-requiring-cave-willing.trycloudflare.com/auth/shopify/callback",
  "https://hrs-requiring-cave-willing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
