api_version = "2025-10"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "limiter-collection-block"
uid = "1a0e8b75-a633-18fd-d87b-68a3dee7e810040dfbff"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/BlockExtension.jsx"
# The target used here must match the target used in the module file (./src/BlockExtension.jsx)
target = "admin.collection-details.block.render"


# Valid extension targets:
# - admin.abandoned-checkout-details.block.render
# - admin.collection-details.block.render
# - admin.customer-details.block.render
# - admin.draft-order-details.block.render
# - admin.order-details.block.render
# - admin.product-details.block.render
# - admin.product-variant-details.block.render
